# Data Injestion and Feature Extraction

The purpose of this notebook is as follows:

1) To showcase the data injestion from various online sources to form the required data table/panel.

2) Followed by creating as many functions as required to further streamline the process for later use.

### Task:-

1) List NUTS2 Regions (DONE)

2) Get GDP per region (DONE) - Unit: Euros per Inhabitants

3) Get Corporate Tax per country (DONE)

4) Education Level per NUTS2 region (DONE)

5) Water Level Nuts 1 region (DONE)

6) Add Soverign Territories - 
    Task looks simple but is one of the challenging problem and the reason for it as follows, the data that we are capturing here is directly from the EU statisitcal office and as these countries are not included here it is a seprate task to find the data that will match these units in all the categories such as education, water levels etc.

7) Climate Conditons (DONE)

8) Data similar to NUTs2 level in US

### My Approach

The idea is to rely on not only sources which are authentic but also a manner in which the data injestion method can be entirely automated with API and request calls.

Though this handicap can result in not aquiring all the categories of data mentioned above,but it will be certianly more valuable as these tasks can be automated and a real time data analysis in the future can be done easily

### Importing Libraries

In [1]:
import pandas as pd
import eurostat as es
import numpy as np
import matplotlib as plt
import seaborn as se
import re

### Step 1: Get the EU Nuts 2 Region Data and GDP

The "Eurostat" python library is directly linked to the offical EU website which contains reliable and latest information regarding all the diffrent regions in the EU in various scale levels.

Eurostat is the statistical office of the European Union.

The link to the website is as follows:-
https://ec.europa.eu/eurostat/en/web/main/data/database

#### Mehtod 1: TSV

In [2]:
toc_df = es.get_data_df('nama_10r_2gdp')

In [3]:
pd.set_option('display.max_rows', 100)
toc_df

,unit,geo\time,2019,2018,2017,2016,2015,2014,2013,2012,...,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000
0,EUR_HAB,AL,4800.0,4500.0,4000.0,3700.0,3600.0,3500.0,3300.0,3300.0,...,3000.0,3000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,EUR_HAB,AL0,4800.0,4500.0,4000.0,3700.0,3600.0,3500.0,3300.0,3300.0,...,3000.0,3000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,EUR_HAB,AL01,3900.0,3600.0,3300.0,3100.0,2900.0,2700.0,2700.0,2700.0,...,2400.0,2300.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,EUR_HAB,AL02,5700.0,5400.0,4900.0,4400.0,4300.0,4100.0,3900.0,3900.0,...,4000.0,4000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,EUR_HAB,AL03,4300.0,4000.0,3600.0,3400.0,3300.0,3400.0,3200.0,3100.0,...,2400.0,2500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3073,PPS_HAB_EU27_2020,TRB2,25.0,25.0,26.0,26.0,26.0,25.0,24.0,26.0,...,18.0,18.0,17.0,17.0,16.0,15.0,NaN,NaN,NaN,NaN
3074,PPS_HAB_EU27_2020,TRC,30.0,32.0,33.0,33.0,34.0,33.0,32.0,29.0,...,23.0,23.0,22.0,22.0,21.0,21.0,NaN,NaN,NaN,NaN
3075,PPS_HAB_EU27_2020,TRC1,38.0,41.0,42.0,42.0,44.0,41.0,39.0,35.0,...,26.0,27.0,27.0,27.0,26.0,25.0,NaN,NaN,NaN,NaN
3076,PPS_HAB_EU27_2020,TRC2,23.0,24.0,27.0,27.0,29.0,27.0,27.0,26.0,...,20.0,20.0,21.0,21.0,20.0,20.0,NaN,NaN,NaN,NaN
3077,PPS_HAB_EU27_2020,TRC3,30.0,31.0,33.0,31.0,32.0,32.0,30.0,29.0,...,22.0,21.0,20.0,20.0,19.0,18.0,NaN,NaN,NaN,NaN

The above method es.get_data_df grabs the data from a TSV format which in our case, where we want to isolate induvidual NUTS2 region is not useful, hence other method will be explored. 

The reason to showcase this data is to keep it as a reminder to come back to find the use case for this format of the data

#### Method 2: SDMX ( 1 obs = 1 row)

In [4]:
dims = es.get_sdmx_dims('nama_10r_2gdp')
dims

['FREQ', 'GEO', 'INDICATORS', 'OBS_FLAG', 'TIME', 'UNIT']

In [5]:
Freq = es.get_sdmx_dic('nama_10r_2gdp', 'FREQ')
Freq

{'A': 'Annual',
 'D': 'Daily',
 'H': 'Half-year',
 'M': 'Monthly',
 'Q': 'Quarterly',
 'S': 'Semi-annual',
 'W': 'Weekly'}

In [6]:
Geo = es.get_sdmx_dic('nama_10r_2gdp', 'GEO')

In [7]:
Unit = es.get_sdmx_dic('nama_10r_2gdp', 'UNIT')
Unit

{'EUR_HAB': 'Euro per inhabitant',
 'EUR_HAB_EU27_2020': 'Euro per inhabitant in percentage of the EU27 (from 2020) average',
 'MIO_EUR': 'Million euro',
 'MIO_NAC': 'Million units of national currency',
 'MIO_PPS_EU27_2020': 'Million purchasing power standards (PPS, EU27 from 2020)',
 'PPS_EU27_2020_HAB': 'Purchasing power standard (PPS, EU27 from 2020), per inhabitant',
 'PPS_HAB_EU27_2020': 'Purchasing power standard (PPS, EU27 from 2020), per inhabitant in percentage of the EU27 (from 2020) average'}

In [8]:
OBS = es.get_sdmx_dic('nama_10r_2gdp', 'OBS_FLAG')
OBS

{'b': 'break in time series',
 'c': 'confidential',
 'd': 'definition differs, see metadata',
 'e': 'estimated',
 'f': 'forecast',
 'i': 'see metadata (phased out)',
 'n': 'not significant',
 'p': 'provisional',
 'r': 'revised',
 's': 'Eurostat estimate (phased out)',
 'u': 'low reliability',
 'z': 'not applicable'}

In [9]:
filter_pars = {'FREQ': ['A'], 'UNIT':['EUR_HAB']}
EU_nuts2_sdmx = es.get_sdmx_data_df('nama_10r_2gdp','2010', '2020',filter_pars,flags=False, verbose = True)

Progress: 100.0%

The above method showcased is the most reliable method to get the data we are looking and it also in the format which is required to move ahead in our analysis.

Furthermore, it can be noticed that a country is also showcased along with the NUTS2 region which should be seprated

In [10]:
EU_nuts2 = EU_nuts2_sdmx[EU_nuts2_sdmx.GEO.str.contains(r'[0-9]')]
EU_nuts2 = EU_nuts2.reset_index(drop=True)

In [11]:
EU_r = EU_nuts2_sdmx[~EU_nuts2_sdmx.GEO.str.contains(r'[0-9]')]
EU_r =  EU_r.reset_index(drop=True)
EU_r

,UNIT,GEO,FREQ,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010
0,EUR_HAB,AL,A,4800.0,4500.0,4000.0,3700.0,3600.0,3500.0,3300.0,3300.0,3200.0,3100.0
1,EUR_HAB,AT,A,44800.0,43600.0,42000.0,40900.0,39900.0,39000.0,38200.0,37800.0,37000.0,35400.0
2,EUR_HAB,ATZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,EUR_HAB,ATZZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,EUR_HAB,BE,A,41400.0,40300.0,39100.0,38000.0,37000.0,36000.0,35200.0,34800.0,34100.0,33300.0
5,EUR_HAB,BEZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,EUR_HAB,BEZZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,EUR_HAB,BG,A,8800.0,8000.0,7400.0,6800.0,6400.0,5900.0,5800.0,5800.0,5600.0,5100.0
8,EUR_HAB,CY,A,25300.0,24600.0,23400.0,22200.0,21100.0,20400.0,20900.0,22500.0,23300.0,23400.0
9,EUR_HAB,CZ,A,21000.0,19800.0,18300.0,16800.0,16100.0,15000.0,15200.0,15500.0,15700.0,15000.0
10,EUR_HAB,DE,A,41500.0,40500.0,39400.0,38100.0,37000.0,36100.0,34900.0,34100.0,33600.0,31900.0
11,EUR_HAB,DEA,A,39900.0,39000.0,37800.0,36500.0,35900.0,35100.0,33800.0,33200.0,32900.0,31500.0
12,EUR_HAB,DEB,A,35500.0,35200.0,34500.0,33600.0,33000.0,31900.0,30800.0,30200.0,29400.0,28100.0
13,EUR_HAB,DEC,A,36800.0,36100.0,35500.0,34500.0,34300.0,33600.0,32000.0,32100.0,31800.0,29900.0
14,EUR_HAB,DED,A,31600.0,30600.0,29800.0,28700.0,27900.0,27000.0,25700.0,25000.0,24500.0,23300.0
15,EUR_HAB,DEE,A,28900.0,28000.0,27300.0,26400.0,25600.0,25100.0,24400.0,23900.0,22700.0,22100.0
16,EUR_HAB,DEF,A,33900.0,32900.0,32000.0,30500.0,29800.0,29400.0,28500.0,28100.0,27100.0,26100.0
17,EUR_HAB,DEG,A,29900.0,29000.0,28400.0,27400.0,26600.0,26000.0,24700.0,23600.0,23100.0,21700.0
18,EUR_HAB,DK,A,53800.0,52200.0,51100.0,49400.0,48000.0,47100.0,46100.0,45500.0,44500.0,43800.0
19,EUR_HAB,DKZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,EUR_HAB,DKZZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,EUR_HAB,EE,A,21200.0,19700.0,18100.0,16700.0,15800.0,15300.0,14400.0,13600.0,12700.0,11100.0
22,EUR_HAB,EL,A,17100.0,16700.0,16500.0,16200.0,16300.0,16300.0,16400.0,17100.0,18300.0,20200.0
23,EUR_HAB,ES,A,26400.0,25800.0,25000.0,24000.0,23200.0,22200.0,21900.0,22000.0,22800.0,23000.0
24,EUR_HAB,ESZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,EUR_HAB,ESZZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,EUR_HAB,FI,A,43600.0,42300.0,41100.0,39600.0,38600.0,37900.0,37600.0,37100.0,36700.0,35100.0
27,EUR_HAB,FIZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,EUR_HAB,FIZZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,EUR_HAB,FR,A,36000.0,35100.0,34300.0,33400.0,33000.0,NaN,NaN,NaN,NaN,NaN
30,EUR_HAB,FRB,A,29200.0,28800.0,28100.0,27500.0,27400.0,NaN,NaN,NaN,NaN,NaN
31,EUR_HAB,FRC,A,28000.0,27900.0,27200.0,26400.0,26400.0,NaN,NaN,NaN,NaN,NaN
32,EUR_HAB,FRD,A,28600.0,28500.0,27900.0,27800.0,27600.0,NaN,NaN,NaN,NaN,NaN
33,EUR_HAB,FRE,A,28000.0,27700.0,27000.0,26300.0,26200.0,NaN,NaN,NaN,NaN,NaN
34,EUR_HAB,FRF,A,29100.0,28900.0,28200.0,27500.0,27400.0,NaN,NaN,NaN,NaN,NaN
35,EUR_HAB,FRG,A,32200.0,30900.0,30200.0,29600.0,29200.0,NaN,NaN,NaN,NaN,NaN
36,EUR_HAB,FRH,A,30300.0,29500.0,29000.0,28100.0,27700.0,NaN,NaN,NaN,NaN,NaN
37,EUR_HAB,FRI,A,30300.0,29400.0,28600.0,28000.0,27700.0,NaN,NaN,NaN,NaN,NaN
38,EUR_HAB,FRJ,A,30700.0,29300.0,28500.0,27900.0,27500.0,NaN,NaN,NaN,NaN,NaN
39,EUR_HAB,FRK,A,35500.0,33900.0,33100.0,32200.0,31600.0,NaN,NaN,NaN,NaN,NaN
40,EUR_HAB,FRL,A,33600.0,32800.0,32100.0,31200.0,30800.0,NaN,NaN,NaN,NaN,NaN
41,EUR_HAB,FRM,A,29200.0,27600.0,26700.0,26200.0,26200.0,NaN,NaN,NaN,NaN,NaN
42,EUR_HAB,FRY,A,20900.0,20300.0,19900.0,19500.0,19200.0,NaN,NaN,NaN,NaN,NaN
43,EUR_HAB,FRZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,EUR_HAB,FRZZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,EUR_HAB,HR,A,13300.0,12700.0,11900.0,11200.0,10600.0,10200.0,10300.0,10300.0,10500.0,10500.0
46,EUR_HAB,HU,A,14900.0,13900.0,13000.0,11800.0,11400.0,10700.0,10300.0,10100.0,10200.0,10000.0
47,EUR_HAB,HUZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,EUR_HAB,HUZZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,EUR_HAB,IE,A,72300.0,67300.0,62600.0,57000.0,56000.0,41900.0,38900.0,38100.0,37300.0,36800.0
50,EUR_HAB,IT,A,29700.0,29300.0,28700.0,28000.0,27300.0,26800.0,26600.0,26900.0,27500.0,26900.0
51,EUR_HAB,ITC,A,36700.0,36300.0,35500.0,34500.0,33600.0,32900.0,32500.0,32900.0,33800.0,33100.0
52,EUR_HAB,ITF,A,19600.0,19400.0,19000.0,18600.0,18300.0,17900.0,17900.0,18200.0,18300.0,18100.0
53,EUR_HAB,ITG,A,18800.0,18500.0,18300.0,17900.0,17800.0,17400.0,17600.0,18000.0,18100.0,18000.0
54,EUR_HAB,ITH,A,35500.0,35100.0,34300.0,33400.0,32400.0,31800.0,31400.0,31300.0,31900.0,30900.0
55,EUR_HAB,ITI,A,32100.0,31700.0,31100.0,30500.0,29500.0,29300.0,29200.0,29900.0,30800.0,30300.0
56,EUR_HAB,ITZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,EUR_HAB,ITZZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,EUR_HAB,LT,A,17500.0,16200.0,14900.0,13600.0,12900.0,12500.0,11800.0,11200.0,10300.0,9100.0
59,EUR_HAB,LU,A,102200.0,98600.0,95200.0,93900.0,91400.0,89200.0,85300.0,83000.0,83100.0,79200.0
60,EUR_HAB,LV,A,15900.0,15100.0,13900.0,12900.0,12400.0,11800.0,11400.0,10900.0,9900.0,8500.0
61,EUR_HAB,LVZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,EUR_HAB,LVZZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,EUR_HAB,ME,A,8000.0,7500.0,6900.0,6400.0,5900.0,5600.0,5400.0,5100.0,5300.0,5000.0
64,EUR_HAB,MK,A,NaN,5200.0,4800.0,4700.0,4400.0,4100.0,3900.0,3700.0,3700.0,3500.0
65,EUR_HAB,MT,A,26700.0,25800.0,24900.0,23200.0,22400.0,20100.0,18600.0,17500.0,16600.0,16400.0
66,EUR_HAB,MTZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,EUR_HAB,MTZZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,EUR_HAB,NL,A,46700.0,44900.0,43100.0,41600.0,40700.0,39800.0,39300.0,39000.0,39000.0,38500.0
69,EUR_HAB,NLZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,EUR_HAB,NLZZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,EUR_HAB,NO,A,NaN,69700.0,67000.0,63700.0,67000.0,73200.0,77400.0,79000.0,72300.0,66200.0
72,EUR_HAB,NOZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,EUR_HAB,NOZZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,EUR_HAB,PL,A,13900.0,13000.0,12200.0,11100.0,11200.0,10600.0,10200.0,10100.0,9900.0,9400.0
75,EUR_HAB,PT,A,20700.0,20000.0,19000.0,18100.0,17400.0,16600.0,16300.0,16000.0,16700.0,17000.0
76,EUR_HAB,PTZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,EUR_HAB,PTZZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,EUR_HAB,RO,A,11500.0,10500.0,9600.0,8600.0,8100.0,7600.0,7200.0,6600.0,6500.0,6200.0
79,EUR_HAB,ROZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,EUR_HAB,ROZZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,EUR_HAB,RS,A,6600.0,6100.0,5600.0,5200.0,5000.0,5000.0,5100.0,4700.0,NaN,NaN
82,EUR_HAB,RSZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,EUR_HAB,RSZZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,EUR_HAB,SE,A,46200.0,46300.0,47700.0,47000.0,46500.0,45300.0,46000.0,45200.0,43700.0,40000.0
85,EUR_HAB,SEZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,EUR_HAB,SEZZ,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,EUR_HAB,SI,A,23200.0,22100.0,20800.0,19600.0,18800.0,18300.0,17700.0,17600.0,18100.0,17700.0
88,EUR_HAB,SK,A,17200.0,16400.0,15500.0,14900.0,14700.0,14100.0,13800.0,13600.0,13200.0,12600.0
89,EUR_HAB,TR,A,8200.0,8100.0,9500.0,9900.0,9900.0,9200.0,9500.0,9100.0,8100.0,8000.0
90,EUR_HAB,TRA,A,4500.0,4300.0,5200.0,5500.0,5300.0,4800.0,5100.0,5000.0,4400.0,4500.0
91,EUR_HAB,TRB,A,4100.0,3900.0,4700.0,4800.0,4700.0,4400.0,4600.0,4600.0,4000.0,3900.0
92,EUR_HAB,TRC,A,4100.0,4000.0,4800.0,4900.0,5000.0,4600.0,4800.0,4500.0,4000.0,3900.0

Renaming the column of year to GDP_year

In [12]:
EU_nuts2_GDP_IH = EU_nuts2.rename({2010: "GDP_2010",2011: "GDP_2011",2012: "GDP_2012",2013: "GDP_2013",2014: "GDP_2014",
                  2015: "GDP_2015",2016: "GDP_2016",2017: "GDP_2017",2018: "GDP_2018",2019: "GDP_2019","UNIT":"Unit_1"},axis = 1)

In [13]:
filter_pars = {'FREQ': ['A'], 'UNIT':['MIO_EUR']}
EU_nuts2_sdmx_Mil = es.get_sdmx_data_df('nama_10r_2gdp','2010', '2020',filter_pars,flags=False, verbose = True)

Progress: 100.0%

In [14]:
EU_nuts2_Mil = EU_nuts2_sdmx_Mil[EU_nuts2_sdmx_Mil.GEO.str.contains(r'[0-9]')]
EU_nuts2_Mil = EU_nuts2_Mil.reset_index(drop=True)

In [15]:
EU_nuts2_GDP_Mil = EU_nuts2_Mil.rename({2010: "GDP_2010_M",2011: "GDP_2011_M",2012: "GDP_2012_M",2013: "GDP_2013_M",2014: "GDP_2014_M",
                  2015: "GDP_2015_M",2016: "GDP_2016_M",2017: "GDP_2017_M",2018: "GDP_2018_M",2019: "GDP_2019_M","UNIT":"Unit_2"},axis = 1)

In [16]:
EU_NUTS2_GDP_ALL = pd.merge(EU_nuts2_GDP_Mil, EU_nuts2_GDP_IH, on='GEO', how='left')
EU_NUTS2_GDP_ALL

,Unit_2,GEO,FREQ_x,GDP_2019_M,GDP_2018_M,GDP_2017_M,GDP_2016_M,GDP_2015_M,GDP_2014_M,GDP_2013_M,...,GDP_2019,GDP_2018,GDP_2017,GDP_2016,GDP_2015,GDP_2014,GDP_2013,GDP_2012,GDP_2011,GDP_2010
0,MIO_EUR,AL0,A,13644.67,12820.09,11559.04,10719.85,10264.11,9968.6,9625.36,...,4800.0,4500.0,4000.0,3700.0,3600.0,3500.0,3300.0,3300.0,3200.0,3100.0
1,MIO_EUR,AL01,A,3142.06,2953.02,2707.01,2549.18,2418.75,2290.45,2276.67,...,3900.0,3600.0,3300.0,3100.0,2900.0,2700.0,2700.0,2700.0,2600.0,2600.0
2,MIO_EUR,AL02,A,6735.64,6323.61,5640.05,5050.74,4837.09,4535.08,4319.08,...,5700.0,5400.0,4900.0,4400.0,4300.0,4100.0,3900.0,3900.0,3900.0,4000.0
3,MIO_EUR,AL03,A,3766.97,3543.46,3211.98,3119.93,3008.27,3143.07,3029.61,...,4300.0,4000.0,3600.0,3400.0,3300.0,3400.0,3200.0,3100.0,3000.0,2600.0
4,MIO_EUR,AT1,A,171326.17,166154.65,159941.08,155864.94,149210.45,144536.29,141127.14,...,44200.0,43100.0,41700.0,41000.0,39800.0,39100.0,38500.0,38300.0,37800.0,36600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,MIO_EUR,TRB1,A,8684.94,8288.39,9877.99,10171.94,9982.53,9105.19,9560.26,...,4900.0,4800.0,5700.0,6000.0,5900.0,5400.0,5700.0,5400.0,4900.0,4800.0
361,MIO_EUR,TRB2,A,7388.44,6898.96,7986.81,8309.77,8003.34,7509.0,7759.79,...,3400.0,3200.0,3800.0,3900.0,3800.0,3600.0,3700.0,4000.0,3200.0,3200.0
362,MIO_EUR,TRC1,A,14989.71,14637.14,16518.67,17015.64,17015.04,14908.19,14946.37,...,5300.0,5300.0,6000.0,6300.0,6400.0,5700.0,5900.0,5400.0,4600.0,4500.0
363,MIO_EUR,TRC2,A,12131.71,11630.85,14073.93,14683.24,14740.71,13221.9,14050.38,...,3200.0,3100.0,3900.0,4100.0,4200.0,3800.0,4200.0,3900.0,3600.0,3600.0
364,MIO_EUR,TRC3,A,9653.76,9049.97,10308.14,10092.76,10105.88,9529.04,9685.71,...,4200.0,4000.0,4700.0,4600.0,4700.0,4500.0,4600.0,4400.0,3900.0,3900.0

#### Aquiring Lat/Lon data with respect to NUTS 2 region

Getting the Latitude and Longitude of the regions will further allow us to streamline the data injestion problem and get the climate paramenters by another api call to fill our data

#### Method 1

Eurostat package which contains the geo spatial data is in R and not in python and I was not able to install the purtcular dependicy which is library rpy2>=3.4.5 due to some error in my current setup

And therefore was not able to install the R wrapper which would allow me to call the geo-spatial data directly from the official EU website 

Hence, other methods need to be explored

### Education level- Nuts2

#### Total Number of Enrollement (M/F) excluding early edu development

In [17]:
dims = es.get_sdmx_dims('educ_uoe_enra11')
dims

['FREQ', 'GEO', 'INDICATORS', 'ISCED11', 'OBS_FLAG', 'SEX', 'TIME', 'UNIT']

In [18]:
Freq =  es.get_sdmx_dic('educ_uoe_enra11', 'FREQ')
Freq

{'A': 'Annual',
 'D': 'Daily',
 'H': 'Half-year',
 'M': 'Monthly',
 'Q': 'Quarterly',
 'S': 'Semi-annual',
 'W': 'Weekly'}

In [19]:
Unit =  es.get_sdmx_dic('educ_uoe_enra11', 'UNIT')
Unit

{'NR': 'Number'}

In [20]:
ISCED11 = es.get_sdmx_dic('educ_uoe_enra11', 'ISCED11')
ISCED11

{'ED0': 'Early childhood education',
 'ED02-8': 'All ISCED 2011 levels excluding early childhood educational development',
 'ED1': 'Primary education',
 'ED2': 'Lower secondary education',
 'ED3': 'Upper secondary education',
 'ED4': 'Post-secondary non-tertiary education',
 'ED5': 'Short-cycle tertiary education',
 'ED6': "Bachelor's or equivalent level",
 'ED7': "Master's or equivalent level",
 'ED8': 'Doctoral or equivalent level'}

In [21]:
GEO =  es.get_sdmx_dic('educ_uoe_enra11', 'GEO')

In [22]:
SEX =  es.get_sdmx_dic('educ_uoe_enra11', 'SEX')
SEX

{'F': 'Females', 'M': 'Males', 'T': 'Total'}

In [23]:
filter_pars = {'FREQ': ['A'], 'ISCED11':['ED6'], 'SEX':['T']}
EU_nuts2_sdmx_EDU = es.get_sdmx_data_df('educ_uoe_enra11','2010', '2020',filter_pars,flags=False, verbose = True)

Progress: 100.0%

In [24]:
pd.set_option('display.max_rows', 100)
EU_nuts2_sdmx_EDU

,ISCED11,UNIT,SEX,GEO,FREQ,2019,2018,2017,2016,2015,2014,2013
0,ED6,NR,T,AT,A,197202.0,199236.0,195964.0,192467.0,183768.0,179406.0,180234.0
1,ED6,NR,T,AT1,A,113027.0,115414.0,NaN,110813.0,105550.0,102896.0,103050.0
2,ED6,NR,T,AT11,A,1571.0,1750.0,NaN,1418.0,1366.0,1180.0,1115.0
3,ED6,NR,T,AT12,A,8091.0,9134.0,NaN,6876.0,6631.0,6462.0,6268.0
4,ED6,NR,T,AT13,A,103365.0,104530.0,NaN,102519.0,97554.0,95253.0,95667.0
...,...,...,...,...,...,...,...,...,...,...,...,...
461,ED6,NR,T,UKK,A,128303.0,125574.0,122838.0,117737.0,113622.0,109241.0,106729.0
462,ED6,NR,T,UKL,A,77050.0,77342.0,77483.0,76264.0,75252.0,76843.0,76551.0
463,ED6,NR,T,UKM,A,156540.0,153900.0,150631.0,147474.0,143895.0,142183.0,140879.0
464,ED6,NR,T,UKN,A,34488.0,34307.0,34986.0,35096.0,35389.0,34704.0,34565.0
465,ED6,NR,T,UKZ,A,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
EU_nuts2_Edu = EU_nuts2_sdmx_EDU[EU_nuts2_sdmx_EDU.GEO.str.contains(r'[0-9]')]
EU_nuts2_Edu = EU_nuts2_Edu.reset_index(drop=True)

In [26]:
EU_nuts2_Ed6 = EU_nuts2_Edu.rename({2010: "EDU_2010_ED6",2011: "EDU_2011_ED6",2012: "EDU_2012_ED6",2013: "EDU_2013_ED6",2014: "EDU_2014_ED6",
                  2015: "EDU_2015_ED6",2016: "EDU_2016_ED6",2017: "EDU_2017_ED6",2018: "EDU_2018_ED6",2019: "EDU_2019_ED6"},axis = 1)

In [27]:
filter_pars = {'FREQ': ['A'], 'ISCED11':['ED7'], 'SEX':['T']}
EU_nuts2_sdmx_EDU = es.get_sdmx_data_df('educ_uoe_enra11','2010', '2020',filter_pars,flags=False, verbose = True)
EU_nuts2_Edu = EU_nuts2_sdmx_EDU[EU_nuts2_sdmx_EDU.GEO.str.contains(r'[0-9]')]
EU_nuts2_Edu = EU_nuts2_Edu.reset_index(drop=True)
EU_nuts2_Ed7 = EU_nuts2_Edu.rename({2010: "EDU_2010_ED7",2011: "EDU_2011_ED7",2012: "EDU_2012_ED7",2013: "EDU_2013_ED7",2014: "EDU_2014_ED7",
                  2015: "EDU_2015_ED7",2016: "EDU_2016_ED7",2017: "EDU_2017_ED7",2018: "EDU_2018_ED7",2019: "EDU_2019_ED7"},axis = 1)

Progress: 100.0%

In [28]:
filter_pars = {'FREQ': ['A'], 'ISCED11':['ED8'], 'SEX':['T']}
EU_nuts2_sdmx_EDU = es.get_sdmx_data_df('educ_uoe_enra11','2010', '2020',filter_pars,flags=False, verbose = True)
EU_nuts2_Edu = EU_nuts2_sdmx_EDU[EU_nuts2_sdmx_EDU.GEO.str.contains(r'[0-9]')]
EU_nuts2_Edu = EU_nuts2_Edu.reset_index(drop=True)
EU_nuts2_Ed8 = EU_nuts2_Edu.rename({2010: "EDU_2010_ED8",2011: "EDU_2011_ED8",2012: "EDU_2012_ED8",2013: "EDU_2013_ED8",2014: "EDU_2014_ED8",
                  2015: "EDU_2015_ED8",2016: "EDU_2016_ED8",2017: "EDU_2017_ED8",2018: "EDU_2018_ED8",2019: "EDU_2019_ED8"},axis = 1)

Progress: 100.0%

In [29]:
EU_NUTS2_EDU_ALL = pd.merge(EU_nuts2_Ed7,EU_nuts2_Ed6, on='GEO', how='left')
EU_NUTS2_EDU_ALL = pd.merge(EU_nuts2_Ed8,EU_NUTS2_EDU_ALL,on='GEO', how='left')
pd.set_option('display.max_columns', None)
EU_NUTS2_EDU_ALL

,ISCED11,UNIT,SEX,GEO,FREQ,EDU_2019_ED8,EDU_2018_ED8,EDU_2017_ED8,EDU_2016_ED8,EDU_2015_ED8,EDU_2014_ED8,EDU_2013_ED8,ISCED11_x,UNIT_x,SEX_x,FREQ_x,EDU_2019_ED7,EDU_2018_ED7,EDU_2017_ED7,EDU_2016_ED7,EDU_2015_ED7,EDU_2014_ED7,EDU_2013_ED7,ISCED11_y,UNIT_y,SEX_y,FREQ_y,EDU_2019_ED6,EDU_2018_ED6,EDU_2017_ED6,EDU_2016_ED6,EDU_2015_ED6,EDU_2014_ED6,EDU_2013_ED6
0,ED8,NR,T,AT1,A,10625.0,11350.0,NaN,13412.0,13733.0,13920.0,14395.0,ED7,NR,T,A,76419.0,76482.0,NaN,75707.0,76682.0,76049.0,75890.0,ED6,NR,T,A,113027.0,115414.0,NaN,110813.0,105550.0,102896.0,103050.0
1,ED8,NR,T,AT11,A,0.0,0.0,NaN,0.0,0.0,0.0,0.0,ED7,NR,T,A,2593.0,2097.0,NaN,1350.0,1243.0,1128.0,718.0,ED6,NR,T,A,1571.0,1750.0,NaN,1418.0,1366.0,1180.0,1115.0
2,ED8,NR,T,AT12,A,24.0,17.0,NaN,4.0,2.0,3.0,3.0,ED7,NR,T,A,12568.0,12308.0,NaN,11301.0,10815.0,9905.0,8641.0,ED6,NR,T,A,8091.0,9134.0,NaN,6876.0,6631.0,6462.0,6268.0
3,ED8,NR,T,AT13,A,10601.0,11333.0,NaN,13408.0,13731.0,13917.0,14392.0,ED7,NR,T,A,61258.0,62077.0,NaN,63055.0,64624.0,65016.0,66531.0,ED6,NR,T,A,103365.0,104530.0,NaN,102519.0,97554.0,95253.0,95667.0
4,ED8,NR,T,AT2,A,3792.0,4060.0,NaN,4410.0,4520.0,4625.0,4930.0,ED7,NR,T,A,22063.0,23346.0,NaN,25252.0,25944.0,26700.0,26474.0,ED6,NR,T,A,37175.0,37106.0,NaN,35793.0,34687.0,33837.0,34543.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,ED8,NR,T,TRB1,A,2200.0,NaN,NaN,1778.0,1563.0,1175.0,1776.0,ED7,NR,T,A,12232.0,NaN,NaN,10590.0,8989.0,7526.0,6669.0,ED6,NR,T,A,66516.0,NaN,NaN,60517.0,56684.0,51946.0,46955.0
334,ED8,NR,T,TRB2,A,587.0,NaN,NaN,297.0,354.0,139.0,462.0,ED7,NR,T,A,7296.0,NaN,NaN,6936.0,5420.0,3966.0,3878.0,ED6,NR,T,A,22082.0,NaN,NaN,22525.0,21751.0,19750.0,17698.0
335,ED8,NR,T,TRC1,A,982.0,NaN,NaN,1060.0,942.0,433.0,639.0,ED7,NR,T,A,10701.0,NaN,NaN,12118.0,9506.0,8269.0,7202.0,ED6,NR,T,A,44568.0,NaN,NaN,44763.0,40291.0,34855.0,30372.0
336,ED8,NR,T,TRC2,A,870.0,NaN,NaN,835.0,643.0,103.0,1049.0,ED7,NR,T,A,8273.0,NaN,NaN,7901.0,6394.0,3888.0,5452.0,ED6,NR,T,A,30258.0,NaN,NaN,29746.0,29157.0,28546.0,27530.0
337,ED8,NR,T,TRC3,A,93.0,NaN,NaN,64.0,51.0,15.0,0.0,ED7,NR,T,A,3059.0,NaN,NaN,2046.0,1351.0,515.0,129.0,ED6,NR,T,A,20053.0,NaN,NaN,13489.0,11072.0,9111.0,7230.0

#### Percenatge of Pupil/Student population in a NUTS2 lvl

In [30]:
dims = es.get_sdmx_dims('educ_regind')
dims

['FREQ', 'GEO', 'INDICATORS', 'INDIC_ED', 'OBS_FLAG', 'TIME']

In [31]:
INDIC_ED = es.get_sdmx_dic('educ_regind', 'INDIC_ED')
INDIC_ED

{'R02_1': 'Students at ISCED level 3 (GEN) - as % of all students at ISCED level 3 at regional level',
 'R03_1': 'Students at ISCED levels 5-6 - as % of all pupils and students at regional level',
 'R03_2': 'Students in tertiary education (ISCED 5-6) - as % of the population aged 20-24 years at regional level',
 'R04_1': 'Ratio of the proportion of students (ISCED 5-6) over the proportion of the population by NUTS 1 and NUTS 2 regions',
 'R04_2': 'Students (ISCED 5-6) at regional level - as % of total country level students (ISCED 5-6)',
 'R04_3': 'Students (all ISCED levels) aged 17 at regional level - as % of corresponding age population',
 'R04_4': 'Pupils and Students in all levels of education (ISCED 0-6) - as % of total population at regional level',
 'R05_1': 'Participation rates of 4-years-olds in education at regional level',
 'R05_2': 'Pupils and Students in upper secondary and post-secondary non-tertiary education (ISCED 3-4) - as % of the population aged 15-24 years at regional level',
 'R05_3': 'Pupils in primary and lower secondary education (ISCED 1-2) - as % of total population at regional level'}

In [32]:
filter_pars = {'FREQ': ['A'], 'INDIC_ED':['R04_4']}
EU_nuts2_sdmx_EDU_Percentage = es.get_sdmx_data_df('educ_regind','2010', '2020',filter_pars,flags=False, verbose = True)

Progress: 100.0%

In [33]:
EU_nuts2_sdmx_EDU_Percentage

    INDIC_ED   GEO FREQ  2012  2011  2010
0      R04_4    AT    A  20.5  20.5  20.6
1      R04_4   AT1    A  21.2  21.0  21.1
2      R04_4  AT11    A  15.9  15.9  16.1
3      R04_4  AT12    A  17.0  17.0  17.1
4      R04_4  AT13    A  26.0  25.5  25.7
..       ...   ...  ...   ...   ...   ...
392    R04_4   UKK    A  20.4  20.5  20.3
393    R04_4   UKL    A  22.5  23.1  22.4
394    R04_4   UKM    A  22.0  20.5  22.1
395    R04_4   UKN    A  25.0  25.5  25.0
396    R04_4  UKN0    A  25.0  25.5  25.0

[397 rows x 6 columns]

This data with respect to the student population does not seems compelete, therefore wont be worked further

#### Young people neither in employment nor in education and training by sex and NUTS 2 regions

In [34]:
dims = es.get_sdmx_dims('edat_lfse_22')
dims

['AGE',
 'FREQ',
 'GEO',
 'INDICATORS',
 'OBS_FLAG',
 'SEX',
 'TIME',
 'TRAINING',
 'UNIT',
 'WSTATUS']

In [35]:
AGE = es.get_sdmx_dic('edat_lfse_22', 'AGE')
AGE

{'Y15-24': 'From 15 to 24 years',
 'Y15-29': 'From 15 to 29 years',
 'Y18-24': 'From 18 to 24 years'}

In [36]:
Train = es.get_sdmx_dic('edat_lfse_22', 'TRAINING')
Train

{'NO_FE_NO_NFE': 'Neither formal nor non-formal education or training'}

In [37]:
filter_pars = {'FREQ': ['A'], 'AGE':['Y15-29'] ,'TRAINING':['NO_FE_NO_NFE'],'SEX':['T']}
EU_nuts2_sdmx_NO_FE_NO_NFE = es.get_sdmx_data_df('edat_lfse_22','2010', '2020',filter_pars,flags=False, verbose = True)

Progress: 100.0%

In [38]:
EU_nuts2_NO_FE_NO_NFE = EU_nuts2_sdmx_NO_FE_NO_NFE[EU_nuts2_sdmx_NO_FE_NO_NFE.GEO.str.contains(r'[0-9]')]
EU_nuts2_NO_FE_NO_NFE = EU_nuts2_NO_FE_NO_NFE.reset_index(drop=True)
EU_nuts2_EDU_NFE = EU_nuts2_NO_FE_NO_NFE.rename({2010: "EDU_2010_NFE",2011: "EDU_2011_NFE",2012: "EDU_2012_NFE",2013: "EDU_2013_NFE",2014: "EDU_2014_NFE",
                  2015: "EDU_2015_NFE",2016: "EDU_2016_NFE",2017: "EDU_2017_NFE",2018: "EDU_2018_NFE",2019: "EDU_2019_NFE"},axis = 1)

In [39]:
EU_NUTS2_EDU_ALL_1 = pd.merge(EU_nuts2_EDU_NFE,EU_NUTS2_EDU_ALL,on='GEO', how='left')
EU_NUTS2_EDU_ALL_2 = EU_NUTS2_EDU_ALL_1.loc[0:337,:]
EU_NUTS2_EDU_ALL_2

C:\Users\venka\AppData\Local\Temp/ipykernel_33700/2186078760.py:1: FutureWarning: Passing 'suffixes' which cause duplicate columns {'SEX_y', 'UNIT_y', 'FREQ_y'} in the result is deprecated and will raise a MergeError in a future version.
  EU_NUTS2_EDU_ALL_1 = pd.merge(EU_nuts2_EDU_NFE,EU_NUTS2_EDU_ALL,on='GEO', how='left')

,UNIT_x,SEX_x,WSTATUS,AGE,TRAINING,GEO,FREQ_x,2020,EDU_2019_NFE,EDU_2018_NFE,EDU_2017_NFE,EDU_2016_NFE,EDU_2015_NFE,EDU_2014_NFE,EDU_2013_NFE,EDU_2012_NFE,EDU_2011_NFE,EDU_2010_NFE,ISCED11,UNIT_y,SEX_y,FREQ_y,EDU_2019_ED8,EDU_2018_ED8,EDU_2017_ED8,EDU_2016_ED8,EDU_2015_ED8,EDU_2014_ED8,EDU_2013_ED8,ISCED11_x,UNIT_x,SEX_x,FREQ_x,EDU_2019_ED7,EDU_2018_ED7,EDU_2017_ED7,EDU_2016_ED7,EDU_2015_ED7,EDU_2014_ED7,EDU_2013_ED7,ISCED11_y,UNIT_y,SEX_y,FREQ_y,EDU_2019_ED6,EDU_2018_ED6,EDU_2017_ED6,EDU_2016_ED6,EDU_2015_ED6,EDU_2014_ED6,EDU_2013_ED6
0,PC,T,NEMP,Y15-29,NO_FE_NO_NFE,AT1,A,10.9,9.9,10.0,9.9,11.2,10.5,11.4,10.1,9.6,10.3,10.1,ED8,NR,T,A,10625.0,11350.0,NaN,13412.0,13733.0,13920.0,14395.0,ED7,NR,T,A,76419.0,76482.0,NaN,75707.0,76682.0,76049.0,75890.0,ED6,NR,T,A,113027.0,115414.0,NaN,110813.0,105550.0,102896.0,103050.0
1,PC,T,NEMP,Y15-29,NO_FE_NO_NFE,AT11,A,NaN,NaN,9.9,8.0,10.6,8.1,8.9,8.7,8.0,7.6,7.8,ED8,NR,T,A,0.0,0.0,NaN,0.0,0.0,0.0,0.0,ED7,NR,T,A,2593.0,2097.0,NaN,1350.0,1243.0,1128.0,718.0,ED6,NR,T,A,1571.0,1750.0,NaN,1418.0,1366.0,1180.0,1115.0
2,PC,T,NEMP,Y15-29,NO_FE_NO_NFE,AT12,A,8.2,8.3,6.9,7.7,8.3,7.9,10.0,8.0,7.2,9.3,7.8,ED8,NR,T,A,24.0,17.0,NaN,4.0,2.0,3.0,3.0,ED7,NR,T,A,12568.0,12308.0,NaN,11301.0,10815.0,9905.0,8641.0,ED6,NR,T,A,8091.0,9134.0,NaN,6876.0,6631.0,6462.0,6268.0
3,PC,T,NEMP,Y15-29,NO_FE_NO_NFE,AT13,A,13.3,11.5,12.4,11.8,13.4,12.8,12.9,12.0,11.8,11.6,12.4,ED8,NR,T,A,10601.0,11333.0,NaN,13408.0,13731.0,13917.0,14392.0,ED7,NR,T,A,61258.0,62077.0,NaN,63055.0,64624.0,65016.0,66531.0,ED6,NR,T,A,103365.0,104530.0,NaN,102519.0,97554.0,95253.0,95667.0
4,PC,T,NEMP,Y15-29,NO_FE_NO_NFE,AT2,A,8.9,7.8,7.0,7.6,7.4,8.3,8.2,8.8,7.8,6.8,8.8,ED8,NR,T,A,3792.0,4060.0,NaN,4410.0,4520.0,4625.0,4930.0,ED7,NR,T,A,22063.0,23346.0,NaN,25252.0,25944.0,26700.0,26474.0,ED6,NR,T,A,37175.0,37106.0,NaN,35793.0,34687.0,33837.0,34543.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,PC,T,NEMP,Y15-29,NO_FE_NO_NFE,SE33,A,5.2,6.6,6.8,5.1,5.8,6.6,7.2,8.5,8.5,8.1,9.8,ED8,NR,T,A,1376.0,1457.0,1589.0,1693.0,1784.0,1809.0,1813.0,ED7,NR,T,A,12583.0,13077.0,12743.0,12532.0,12270.0,11746.0,11265.0,ED6,NR,T,A,18698.0,18728.0,18584.0,18344.0,18291.0,19427.0,22140.0
334,PC,T,NEMP,Y15-29,NO_FE_NO_NFE,SI0,A,9.2,8.8,8.8,9.3,10.9,12.3,12.9,12.9,11.8,9.4,9.4,ED8,NR,T,A,3089.0,2824.0,2558.0,2331.0,2644.0,3016.0,3606.0,ED7,NR,T,A,20988.0,21517.0,21864.0,22013.0,22594.0,23483.0,26040.0,ED6,NR,T,A,41348.0,41840.0,44124.0,45292.0,48893.0,53019.0,56825.0
335,PC,T,NEMP,Y15-29,NO_FE_NO_NFE,SI01,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ED8,NR,T,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ED7,NR,T,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ED6,NR,T,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
336,PC,T,NEMP,Y15-29,NO_FE_NO_NFE,SI02,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ED8,NR,T,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ED7,NR,T,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ED6,NR,T,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,PC,T,NEMP,Y15-29,NO_FE_NO_NFE,SI03,A,10.6,10.1,10.0,10.0,11.8,13.9,14.8,14.7,13.3,10.9,10.7,ED8,NR,T,A,625.0,529.0,504.0,397.0,444.0,512.0,614.0,ED7,NR,T,A,4622.0,4679.0,4897.0,5128.0,5365.0,5670.0,6057.0,ED6,NR,T,A,11269.0,11823.0,12715.0,12878.0,14280.0,16008.0,17385.0

### Water Data NUTS2 level is not available at Euro Stat

In [40]:
filter_pars = {'FREQ': ['A'],'WAT_PROC':['ABST'],'UNIT':['M3_HAB'],'WAT_SRC':['FGW']}
EU_nuts2_sdmx_WA = es.get_sdmx_data_df('env_wat_abs','2010', '2020',filter_pars,flags=False, verbose = True)
#EU_nuts2_WA = EU_nuts2_sdmx_WA[EU_nuts2_sdmx_WA.GEO.str.contains(r'[0-9]')]
#EU_nuts2_WA = EU_nuts2_WA.reset_index(drop=True)
EU_nuts2_WA_A = EU_nuts2_sdmx_WA.rename({2010: "A_2010_WA",2011: "A_2011_WA",2012: "A_2012_WA",2013: "A_2013_WA",2014: "A_2014_WA",
                  2015: "A_2015_WA",2016: "A_2016_WA",2017: "A_2017_WA",2018: "A_2018_WA",2019: "A_2019_WA"},axis = 1)
EU_nuts2_WA_A

Progress: 100.0%

,UNIT,WAT_PROC,WAT_SRC,GEO,FREQ,A_2018_WA,A_2017_WA,A_2016_WA,A_2015_WA,A_2014_WA,A_2013_WA,A_2012_WA,A_2011_WA,A_2010_WA
0,M3_HAB,ABST,FGW,AL,A,34.57,37.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,M3_HAB,ABST,FGW,AT,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,M3_HAB,ABST,FGW,BA,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,M3_HAB,ABST,FGW,BE,A,NaN,NaN,NaN,56.24,56.5,57.39,57.43,54.76,56.49
4,M3_HAB,ABST,FGW,BG,A,80.35,81.92,78.42,77.52,75.47,76.61,77.19,73.92,75.01
5,M3_HAB,ABST,FGW,CH,A,NaN,NaN,NaN,NaN,NaN,NaN,126.38,NaN,NaN
6,M3_HAB,ABST,FGW,CY,A,179.35,181.33,182.71,177.09,157.34,161.69,179.81,184.58,170.91
7,M3_HAB,ABST,FGW,CZ,A,34.91,34.92,34.38,34.77,34.34,35.31,36.11,36.06,36.06
8,M3_HAB,ABST,FGW,DE,A,NaN,NaN,72.56,NaN,NaN,73.47,NaN,NaN,71.4
9,M3_HAB,ABST,FGW,DK,A,150.86,120.42,119.5,123.78,136.75,135.02,111.47,128.15,123.58
10,M3_HAB,ABST,FGW,EE,A,NaN,187.89,168.7,153.63,151.24,161.19,206.61,224.94,222.01
11,M3_HAB,ABST,FGW,EL,A,579.56,578.86,577.9,516.63,513.25,510.12,506.46,505.11,NaN
12,M3_HAB,ABST,FGW,ES,A,NaN,NaN,137.68,136.37,135.53,130.75,138.75,131.64,142.0
13,M3_HAB,ABST,FGW,FI,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,M3_HAB,ABST,FGW,FR,A,NaN,85.2,82.68,86.73,80.08,85.69,85.91,90.92,92.53
15,M3_HAB,ABST,FGW,HR,A,103.21,102.22,103.41,101.17,98.56,101.93,104.96,103.19,104.51
16,M3_HAB,ABST,FGW,HU,A,52.6,59.49,49.55,49.89,48.15,50.06,50.74,50.37,49.7
17,M3_HAB,ABST,FGW,IE,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,M3_HAB,ABST,FGW,IS,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,M3_HAB,ABST,FGW,IT,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,M3_HAB,ABST,FGW,LT,A,57.99,54.8,54.43,53.72,53.98,53.31,50.13,50.87,50.5
21,M3_HAB,ABST,FGW,LU,A,NaN,NaN,39.91,45.83,48.52,46.79,39.82,43.76,46.41
22,M3_HAB,ABST,FGW,LV,A,56.24,42.81,41.26,40.54,41.72,43.38,41.55,42.91,44.95
23,M3_HAB,ABST,FGW,MK,A,NaN,NaN,NaN,NaN,100.3,NaN,NaN,NaN,NaN
24,M3_HAB,ABST,FGW,MT,A,81.27,90.77,92.31,89.63,98.81,102.96,89.74,94.65,98.88
25,M3_HAB,ABST,FGW,NL,A,69.13,59.4,57.92,58.73,57.34,59.12,56.22,59.39,60.16
26,M3_HAB,ABST,FGW,NO,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,M3_HAB,ABST,FGW,PL,A,66.06,67.36,68.31,68.61,67.8,68.52,69.48,71.79,71.58
28,M3_HAB,ABST,FGW,PT,A,NaN,200.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,M3_HAB,ABST,FGW,RO,A,34.61,32.89,32.13,29.69,27.77,29.02,29.76,29.7,30.75
30,M3_HAB,ABST,FGW,RS,A,70.87,65.41,62.38,67.09,63.96,66.53,70.03,69.32,70.26
31,M3_HAB,ABST,FGW,SE,A,NaN,NaN,NaN,37.45,NaN,NaN,NaN,NaN,36.94
32,M3_HAB,ABST,FGW,SI,A,91.75,91.24,87.25,88.03,88.21,87.96,87.38,90.09,90.47
33,M3_HAB,ABST,FGW,SK,A,62.26,61.54,59.58,60.1,59.32,60.84,62.71,62.01,63.3
34,M3_HAB,ABST,FGW,TR,A,200.22,193.7,191.26,187.91,190.43,179.3,181.47,183.93,181.06
35,M3_HAB,ABST,FGW,UK,A,NaN,NaN,NaN,NaN,31.9,NaN,32.22,34.25,34.43
36,M3_HAB,ABST,FGW,UKC-L,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,M3_HAB,ABST,FGW,XK,A,9.11,8.41,10.05,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
filter_pars = {'FREQ': ['A'],'WAT_PROC':['ABS_PWS'],'WAT_SRC':['FGW'],'UNIT':['M3_HAB']}
EU_nuts2_sdmx_WA = es.get_sdmx_data_df('env_wat_abs','2010', '2020',filter_pars,flags=False, verbose = True)
#EU_nuts2_WA = EU_nuts2_sdmx_WA[EU_nuts2_sdmx_WA.GEO.str.contains(r'[0-9]')]
#EU_nuts2_WA = EU_nuts2_WA.reset_index(drop=True)
EU_nuts2_WA_P = EU_nuts2_sdmx_WA.rename({2010: "P_2010_WA",2011: "P_2011_WA",2012: "P_2012_WA",2013: "P_2013_WA",2014: "P_2014_WA",
                  2015: "P_2015_WA",2016: "P_2016_WA",2017: "P_2017_WA",2018: "P_2018_WA",2019: "P_2019_WA"},axis = 1)
EU_nuts2_WA_P

Progress: 100.0%

,UNIT,WAT_PROC,WAT_SRC,GEO,FREQ,P_2018_WA,P_2017_WA,P_2016_WA,P_2015_WA,P_2014_WA,P_2013_WA,P_2012_WA,P_2011_WA,P_2010_WA
0,M3_HAB,ABS_PWS,FGW,AL,A,28.67,31.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,M3_HAB,ABS_PWS,FGW,AT,A,NaN,NaN,75.86,NaN,NaN,NaN,NaN,NaN,82.02
2,M3_HAB,ABS_PWS,FGW,BA,A,NaN,NaN,NaN,NaN,NaN,NaN,71.21,71.43,73.28
3,M3_HAB,ABS_PWS,FGW,BE,A,NaN,NaN,NaN,41.51,41.21,42.23,41.84,40.52,41.71
4,M3_HAB,ABS_PWS,FGW,BG,A,63.92,65.88,63.47,61.21,59.24,60.82,60.9,59.19,59.43
5,M3_HAB,ABS_PWS,FGW,CH,A,88.87,88.72,89.59,91.41,90.42,92.55,95.67,96.95,96.46
6,M3_HAB,ABS_PWS,FGW,CY,A,23.14,24.57,25.93,27.15,27.97,28.87,30.16,32.15,34.18
7,M3_HAB,ABS_PWS,FGW,CZ,A,28.19,27.99,27.72,28.16,27.81,28.87,29.49,29.69,29.97
8,M3_HAB,ABS_PWS,FGW,DE,A,NaN,NaN,43.79,43.91,43.73,43.45,43.71,NaN,43.21
9,M3_HAB,ABS_PWS,FGW,DK,A,66.85,65.51,67.13,66.49,68.89,70.08,70.41,70.93,72.69
10,M3_HAB,ABS_PWS,FGW,EE,A,NaN,24.13,24.65,16.15,25.09,24.39,24.6,22.75,29.55
11,M3_HAB,ABS_PWS,FGW,EL,A,69.85,69.67,69.57,72.75,72.29,71.78,71.25,71.01,NaN
12,M3_HAB,ABS_PWS,FGW,ES,A,NaN,NaN,35.31,34.34,32.18,34.47,34.05,33.13,34.2
13,M3_HAB,ABS_PWS,FGW,FI,A,NaN,NaN,NaN,NaN,48.8,47.91,48.32,44.65,44.85
14,M3_HAB,ABS_PWS,FGW,FR,A,NaN,54.15,51.53,52.6,53.06,54.6,54.06,55.85,57.49
15,M3_HAB,ABS_PWS,FGW,HR,A,101.31,99.88,101.5,99.37,97.24,100.66,103.53,101.15,102.97
16,M3_HAB,ABS_PWS,FGW,HU,A,37.92,37.03,35.21,35.66,34.08,33.79,34.73,34.58,34.95
17,M3_HAB,ABS_PWS,FGW,IE,A,NaN,21.32,22.22,21.59,25.87,22.13,22.01,21.22,21.76
18,M3_HAB,ABS_PWS,FGW,IS,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,M3_HAB,ABS_PWS,FGW,IT,A,129.45,131.81,131.46,131.49,130.84,133.06,135.09,NaN,NaN
20,M3_HAB,ABS_PWS,FGW,LT,A,48.29,45.18,45.04,44.3,44.33,43.4,40.04,40.61,40.04
21,M3_HAB,ABS_PWS,FGW,LU,A,NaN,NaN,39.91,42.16,44.78,42.42,38.11,40.44,45.41
22,M3_HAB,ABS_PWS,FGW,LV,A,32.24,30.38,30.45,28.86,29.41,29.9,30.09,30.08,28.58
23,M3_HAB,ABS_PWS,FGW,MK,A,NaN,NaN,NaN,NaN,NaN,16.68,16.26,NaN,NaN
24,M3_HAB,ABS_PWS,FGW,MT,A,29.93,31.2,29.99,30.57,32.51,32.64,31.85,31.47,30.87
25,M3_HAB,ABS_PWS,FGW,NL,A,47.93,45.78,45.81,45.37,45.02,45.46,45.05,45.38,45.9
26,M3_HAB,ABS_PWS,FGW,NO,A,22.23,19.72,18.38,NaN,22.71,21.38,20.06,16.06,15.44
27,M3_HAB,ABS_PWS,FGW,PL,A,40.87,38.45,38.82,38.63,37.24,37.2,37.55,37.37,37.49
28,M3_HAB,ABS_PWS,FGW,PT,A,NaN,29.68,23.14,22.71,23.68,26.63,28.3,NaN,NaN
29,M3_HAB,ABS_PWS,FGW,RO,A,NaN,22.7,22.67,20.83,19.55,19.68,20.05,18.71,18.33
30,M3_HAB,ABS_PWS,FGW,RS,A,61.09,55.58,53.87,60.53,59.92,61.51,65.27,65.19,65.78
31,M3_HAB,ABS_PWS,FGW,SE,A,NaN,NaN,NaN,20.01,NaN,NaN,NaN,NaN,22.38
32,M3_HAB,ABS_PWS,FGW,SI,A,81.96,81.32,77.66,78.63,77.92,78.05,77.06,80.38,79.24
33,M3_HAB,ABS_PWS,FGW,SK,A,45.12,45.26,44.25,44.58,44.41,45.76,47.5,47.07,48.4
34,M3_HAB,ABS_PWS,FGW,TR,A,40.46,40.14,37.28,37.13,36.96,40.54,44.14,44.61,44.56
35,M3_HAB,ABS_PWS,FGW,UK,A,NaN,NaN,NaN,NaN,25.86,NaN,26.52,27.66,27.64
36,M3_HAB,ABS_PWS,FGW,UKC-L,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,M3_HAB,ABS_PWS,FGW,XK,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
filter_pars = {'FREQ': ['A'],'WAT_PROC':['ABS_IND'],'WAT_SRC':['FGW'],'UNIT':['M3_HAB']}
EU_nuts2_sdmx_WA = es.get_sdmx_data_df('env_wat_abs','2010', '2020',filter_pars,flags=False, verbose = True)
#EU_nuts2_WA = EU_nuts2_sdmx_WA[EU_nuts2_sdmx_WA.GEO.str.contains(r'[0-9]')]
#EU_nuts2_WA = EU_nuts2_WA.reset_index(drop=True)
EU_nuts2_WA_I = EU_nuts2_sdmx_WA.rename({2010: "I_2010_WA",2011: "I_2011_WA",2012: "I_2012_WA",2013: "I_2013_WA",2014: "I_2014_WA",
                  2015: "I_2015_WA",2016: "I_2016_WA",2017: "I_2017_WA",2018: "I_2018_WA",2019: "I_2019_WA"},axis = 1)
EU_nuts2_WA_I

Progress: 100.0%

,UNIT,WAT_PROC,WAT_SRC,GEO,FREQ,I_2018_WA,I_2017_WA,I_2016_WA,I_2015_WA,I_2014_WA,I_2013_WA,I_2012_WA,I_2011_WA,I_2010_WA
0,M3_HAB,ABS_IND,FGW,AL,A,NaN,0.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,M3_HAB,ABS_IND,FGW,AT,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,M3_HAB,ABS_IND,FGW,BA,A,NaN,NaN,NaN,NaN,NaN,NaN,4.44,3.51,8.32
3,M3_HAB,ABS_IND,FGW,BE,A,NaN,NaN,NaN,4.64,4.55,5.26,5.68,NaN,NaN
4,M3_HAB,ABS_IND,FGW,BG,A,9.94,10.08,9.68,11.65,10.55,9.72,9.75,9.84,9.81
5,M3_HAB,ABS_IND,FGW,CH,A,NaN,NaN,NaN,NaN,NaN,NaN,18.81,NaN,NaN
6,M3_HAB,ABS_IND,FGW,CY,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,M3_HAB,ABS_IND,FGW,CZ,A,2.44,2.39,2.42,2.41,2.39,2.32,2.47,2.45,2.43
8,M3_HAB,ABS_IND,FGW,DE,A,NaN,NaN,8.89,NaN,NaN,9.07,9.31,NaN,9.35
9,M3_HAB,ABS_IND,FGW,DK,A,4.76,3.49,3.6,3.5,3.7,3.3,3.7,4.08,4.0
10,M3_HAB,ABS_IND,FGW,EE,A,NaN,7.06,6.87,NaN,NaN,NaN,4.23,4.51,4.58
11,M3_HAB,ABS_IND,FGW,EL,A,14.55,14.51,14.49,11.46,11.38,11.31,11.22,11.18,NaN
12,M3_HAB,ABS_IND,FGW,ES,A,NaN,NaN,2.39,2.48,3.42,3.44,3.48,3.7,3.94
13,M3_HAB,ABS_IND,FGW,FI,A,1.63,1.49,1.8,1.64,1.98,2.19,2.48,NaN,1.49
14,M3_HAB,ABS_IND,FGW,FR,A,NaN,11.18,10.57,11.1,11.91,10.71,11.1,11.24,11.35
15,M3_HAB,ABS_IND,FGW,HR,A,1.68,2.12,1.69,1.61,1.18,1.13,1.24,1.89,1.4
16,M3_HAB,ABS_IND,FGW,HU,A,NaN,NaN,NaN,NaN,NaN,NaN,3.46,3.81,3.74
17,M3_HAB,ABS_IND,FGW,IE,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,M3_HAB,ABS_IND,FGW,IS,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,M3_HAB,ABS_IND,FGW,IT,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,M3_HAB,ABS_IND,FGW,LT,A,2.28,2.11,1.85,1.72,1.59,1.65,1.63,1.32,1.3
21,M3_HAB,ABS_IND,FGW,LU,A,NaN,NaN,NaN,1.67,2.36,2.9,1.14,1.56,0.8
22,M3_HAB,ABS_IND,FGW,LV,A,4.01,3.94,3.92,3.78,4.03,4.17,3.54,3.47,6.77
23,M3_HAB,ABS_IND,FGW,MK,A,NaN,10.77,NaN,NaN,8.18,11.88,30.49,26.59,56.27
24,M3_HAB,ABS_IND,FGW,MT,A,2.1,2.17,2.22,2.27,2.33,2.37,2.39,2.41,2.42
25,M3_HAB,ABS_IND,FGW,NL,A,7.7,7.62,8.47,8.48,8.38,8.35,8.02,8.31,8.18
26,M3_HAB,ABS_IND,FGW,NO,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,M3_HAB,ABS_IND,FGW,PL,A,4.48,4.3,4.32,4.25,4.15,4.08,4.1,4.15,3.97
28,M3_HAB,ABS_IND,FGW,PT,A,NaN,7.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,M3_HAB,ABS_IND,FGW,RO,A,NaN,7.28,6.93,6.69,6.32,7.49,7.56,9.21,10.64
30,M3_HAB,ABS_IND,FGW,RS,A,4.18,4.12,3.62,3.51,3.29,3.77,3.49,3.34,3.74
31,M3_HAB,ABS_IND,FGW,SE,A,NaN,NaN,NaN,1.33,NaN,NaN,NaN,NaN,1.39
32,M3_HAB,ABS_IND,FGW,SI,A,9.19,9.25,9.01,8.97,9.95,9.52,9.92,9.32,10.75
33,M3_HAB,ABS_IND,FGW,SK,A,10.6,9.6,9.29,9.28,8.99,9.3,9.44,9.03,9.0
34,M3_HAB,ABS_IND,FGW,TR,A,6.9,NaN,6.51,NaN,6.19,NaN,5.65,NaN,8.07
35,M3_HAB,ABS_IND,FGW,UK,A,NaN,NaN,NaN,NaN,2.63,NaN,2.71,2.99,3.1
36,M3_HAB,ABS_IND,FGW,UKC-L,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,M3_HAB,ABS_IND,FGW,XK,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
filter_pars = {'FREQ': ['A']}
EU_nuts2_sdmx_WA = es.get_sdmx_data_df('env_wat_pop','2010', '2020',filter_pars,flags=False, verbose = True)
#EU_nuts2_WA = EU_nuts2_sdmx_WA[EU_nuts2_sdmx_WA.GEO.str.contains(r'[0-9]')]
#EU_nuts2_WA = EU_nuts2_WA.reset_index(drop=True)
EU_nuts2_WA_C = EU_nuts2_sdmx_WA.rename({2010: "C_2010_WA",2011: "C_2011_WA",2012: "C_2012_WA",2013: "C_2013_WA",2014: "C_2014_WA",
                  2015: "C_2015_WA",2016: "C_2016_WA",2017: "C_2017_WA",2018: "C_2018_WA",2019: "C_2019_WA"},axis = 1)
EU_nuts2_WA_C

Progress: 100.0%

,UNIT,WAT_PROC,GEO,FREQ,C_2018_WA,C_2017_WA,C_2016_WA,C_2015_WA,C_2014_WA,C_2013_WA,C_2012_WA,C_2011_WA,C_2010_WA
0,PC,POP_PWS,AL,A,78.0,78.3,80.4,81.0,80.0,80.6,80.0,80.8,80.3
1,PC,POP_PWS,AT,A,NaN,NaN,91.8,NaN,93.0,NaN,NaN,NaN,95.0
2,PC,POP_PWS,BA,A,69.667,67.9,66.2,64.4,64.2,62.0,55.2,NaN,NaN
3,PC,POP_PWS,BE,A,NaN,99.181,99.168,99.143,99.169,99.151,99.139,NaN,NaN
4,PC,POP_PWS,BG,A,99.51,99.42,99.33,99.33,99.31,99.28,99.26,99.19,98.96
5,PC,POP_PWS,CH,A,NaN,NaN,NaN,NaN,NaN,NaN,99.2,NaN,NaN
6,PC,POP_PWS,CY,A,NaN,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
7,PC,POP_PWS,CZ,A,94.7,94.7,94.4,94.2,94.2,93.7,93.6,93.5,92.8
8,PC,POP_PWS,DE,A,NaN,NaN,99.382,99.365,99.349,99.332,99.32,99.309,99.298
9,PC,POP_PWS,DK,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,PC,POP_PWS,EE,A,NaN,82.9,82.8,82.6,82.0,82.2,81.7,81.7,81.6
11,PC,POP_PWS,EL,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,PC,POP_PWS,ES,A,NaN,NaN,100.0,100.0,100.0,100.0,100.0,100.0,100.0
13,PC,POP_PWS,FI,A,NaN,NaN,NaN,NaN,94.0,NaN,92.0,91.0,NaN
14,PC,POP_PWS,FR,A,NaN,NaN,NaN,NaN,NaN,99.0,99.0,99.0,99.0
15,PC,POP_PWS,HR,A,93.0,93.0,93.0,92.16,91.6,90.2,87.5,85.5,83.5
16,PC,POP_PWS,HU,A,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
17,PC,POP_PWS,IE,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,PC,POP_PWS,LT,A,82.436,81.838,81.256,80.24,79.4,77.6,76.0,75.0,74.5
19,PC,POP_PWS,LU,A,NaN,NaN,NaN,99.9,99.9,99.9,99.9,99.9,99.9
20,PC,POP_PWS,MK,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,PC,POP_PWS,MT,A,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
22,PC,POP_PWS,NL,A,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
23,PC,POP_PWS,NO,A,89.315,89.493,89.437,89.481,89.0,89.0,89.0,89.0,88.0
24,PC,POP_PWS,PL,A,92.1,92.0,91.9,91.8,91.6,88.0,87.9,87.6,87.5
25,PC,POP_PWS,PT,A,NaN,92.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,PC,POP_PWS,RO,A,69.4,67.5,65.2,63.7,62.5,61.4,60.3,56.5,55.7
27,PC,POP_PWS,RS,A,87.9,86.9,85.9,85.0,83.7,81.9,80.1,78.2,77.7
28,PC,POP_PWS,SE,A,NaN,NaN,NaN,87.6,87.0,87.0,86.0,86.0,86.8
29,PC,POP_PWS,SK,A,89.3,88.9,88.7,88.3,87.7,87.4,87.0,86.9,86.6
30,PC,POP_PWS,TR,A,98.61,NaN,98.3,NaN,97.4,NaN,98.3,NaN,98.3

In [44]:
EU_WATER_1 = pd.merge(EU_nuts2_WA_A,EU_nuts2_WA_P,on='GEO', how='left')
EU_WATER_2 = pd.merge(EU_nuts2_WA_I,EU_nuts2_WA_C,on='GEO', how='left')
EU_WATER_ALL = pd.merge(EU_WATER_1,EU_WATER_2,on='GEO', how='left')
EU_WATER_ALL

,UNIT_x_x,WAT_PROC_x_x,WAT_SRC_x,GEO,FREQ_x_x,A_2018_WA,A_2017_WA,A_2016_WA,A_2015_WA,A_2014_WA,A_2013_WA,A_2012_WA,A_2011_WA,A_2010_WA,UNIT_y_x,WAT_PROC_y_x,WAT_SRC_y,FREQ_y_x,P_2018_WA,P_2017_WA,P_2016_WA,P_2015_WA,P_2014_WA,P_2013_WA,P_2012_WA,P_2011_WA,P_2010_WA,UNIT_x_y,WAT_PROC_x_y,WAT_SRC,FREQ_x_y,I_2018_WA,I_2017_WA,I_2016_WA,I_2015_WA,I_2014_WA,I_2013_WA,I_2012_WA,I_2011_WA,I_2010_WA,UNIT_y_y,WAT_PROC_y_y,FREQ_y_y,C_2018_WA,C_2017_WA,C_2016_WA,C_2015_WA,C_2014_WA,C_2013_WA,C_2012_WA,C_2011_WA,C_2010_WA
0,M3_HAB,ABST,FGW,AL,A,34.57,37.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M3_HAB,ABS_PWS,FGW,A,28.67,31.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M3_HAB,ABS_IND,FGW,A,NaN,0.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PC,POP_PWS,A,78.0,78.3,80.4,81.0,80.0,80.6,80.0,80.8,80.3
1,M3_HAB,ABST,FGW,AT,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M3_HAB,ABS_PWS,FGW,A,NaN,NaN,75.86,NaN,NaN,NaN,NaN,NaN,82.02,M3_HAB,ABS_IND,FGW,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PC,POP_PWS,A,NaN,NaN,91.8,NaN,93.0,NaN,NaN,NaN,95.0
2,M3_HAB,ABST,FGW,BA,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M3_HAB,ABS_PWS,FGW,A,NaN,NaN,NaN,NaN,NaN,NaN,71.21,71.43,73.28,M3_HAB,ABS_IND,FGW,A,NaN,NaN,NaN,NaN,NaN,NaN,4.44,3.51,8.32,PC,POP_PWS,A,69.667,67.9,66.2,64.4,64.2,62.0,55.2,NaN,NaN
3,M3_HAB,ABST,FGW,BE,A,NaN,NaN,NaN,56.24,56.5,57.39,57.43,54.76,56.49,M3_HAB,ABS_PWS,FGW,A,NaN,NaN,NaN,41.51,41.21,42.23,41.84,40.52,41.71,M3_HAB,ABS_IND,FGW,A,NaN,NaN,NaN,4.64,4.55,5.26,5.68,NaN,NaN,PC,POP_PWS,A,NaN,99.181,99.168,99.143,99.169,99.151,99.139,NaN,NaN
4,M3_HAB,ABST,FGW,BG,A,80.35,81.92,78.42,77.52,75.47,76.61,77.19,73.92,75.01,M3_HAB,ABS_PWS,FGW,A,63.92,65.88,63.47,61.21,59.24,60.82,60.9,59.19,59.43,M3_HAB,ABS_IND,FGW,A,9.94,10.08,9.68,11.65,10.55,9.72,9.75,9.84,9.81,PC,POP_PWS,A,99.51,99.42,99.33,99.33,99.31,99.28,99.26,99.19,98.96
5,M3_HAB,ABST,FGW,CH,A,NaN,NaN,NaN,NaN,NaN,NaN,126.38,NaN,NaN,M3_HAB,ABS_PWS,FGW,A,88.87,88.72,89.59,91.41,90.42,92.55,95.67,96.95,96.46,M3_HAB,ABS_IND,FGW,A,NaN,NaN,NaN,NaN,NaN,NaN,18.81,NaN,NaN,PC,POP_PWS,A,NaN,NaN,NaN,NaN,NaN,NaN,99.2,NaN,NaN
6,M3_HAB,ABST,FGW,CY,A,179.35,181.33,182.71,177.09,157.34,161.69,179.81,184.58,170.91,M3_HAB,ABS_PWS,FGW,A,23.14,24.57,25.93,27.15,27.97,28.87,30.16,32.15,34.18,M3_HAB,ABS_IND,FGW,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PC,POP_PWS,A,NaN,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
7,M3_HAB,ABST,FGW,CZ,A,34.91,34.92,34.38,34.77,34.34,35.31,36.11,36.06,36.06,M3_HAB,ABS_PWS,FGW,A,28.19,27.99,27.72,28.16,27.81,28.87,29.49,29.69,29.97,M3_HAB,ABS_IND,FGW,A,2.44,2.39,2.42,2.41,2.39,2.32,2.47,2.45,2.43,PC,POP_PWS,A,94.7,94.7,94.4,94.2,94.2,93.7,93.6,93.5,92.8
8,M3_HAB,ABST,FGW,DE,A,NaN,NaN,72.56,NaN,NaN,73.47,NaN,NaN,71.4,M3_HAB,ABS_PWS,FGW,A,NaN,NaN,43.79,43.91,43.73,43.45,43.71,NaN,43.21,M3_HAB,ABS_IND,FGW,A,NaN,NaN,8.89,NaN,NaN,9.07,9.31,NaN,9.35,PC,POP_PWS,A,NaN,NaN,99.382,99.365,99.349,99.332,99.32,99.309,99.298
9,M3_HAB,ABST,FGW,DK,A,150.86,120.42,119.5,123.78,136.75,135.02,111.47,128.15,123.58,M3_HAB,ABS_PWS,FGW,A,66.85,65.51,67.13,66.49,68.89,70.08,70.41,70.93,72.69,M3_HAB,ABS_IND,FGW,A,4.76,3.49,3.6,3.5,3.7,3.3,3.7,4.08,4.0,PC,POP_PWS,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,M3_HAB,ABST,FGW,EE,A,NaN,187.89,168.7,153.63,151.24,161.19,206.61,224.94,222.01,M3_HAB,ABS_PWS,FGW,A,NaN,24.13,24.65,16.15,25.09,24.39,24.6,22.75,29.55,M3_HAB,ABS_IND,FGW,A,NaN,7.06,6.87,NaN,NaN,NaN,4.23,4.51,4.58,PC,POP_PWS,A,NaN,82.9,82.8,82.6,82.0,82.2,81.7,81.7,81.6
11,M3_HAB,ABST,FGW,EL,A,579.56,578.86,577.9,516.63,513.25,510.12,506.46,505.11,NaN,M3_HAB,ABS_PWS,FGW,A,69.85,69.67,69.57,72.75,72.29,71.78,71.25,71.01,NaN,M3_HAB,ABS_IND,FGW,A,14.55,14.51,14.49,11.46,11.38,11.31,11.22,11.18,NaN,PC,POP_PWS,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,M3_HAB,ABST,FGW,ES,A,NaN,NaN,137.68,136.37,135.53,130.75,138.75,131.64,142.0,M3_HAB,ABS_PWS,FGW,A,NaN,NaN,35.31,34.34,32.18,34.47,34.05,33.13,34.2,M3_HAB,ABS_IND,FGW,A,NaN,NaN,2.39,2.48,3.42,3.44,3.48,3.7,3.94,PC,POP_PWS,A,NaN,NaN,100.0,100.0,100.0,100.0,100.0,100.0,100.0
13,M3_HAB,ABST,FGW,FI,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M3_HAB,ABS_PWS,FGW,A,NaN,NaN,NaN,NaN,48.8,47.91,48.32,44.65,44.85,M3_HAB,ABS_IND,FGW,A,1.63,1.49,1.8,1.64,1.98,2.19,2.48,NaN,1.49,PC,POP_PWS,A,NaN,NaN,NaN,NaN,94.0,NaN,92.0,91.0,NaN
14,M3_HAB,ABST,FGW,FR,A,NaN,85.2,82.68,86.73,80.08,85.69,85.91,90.92,92.53,M3_HAB,ABS_PWS,FGW,A,NaN,54.15,51.53,52.6,53.06,54.6,54.06,55.85,57.49,M3_HAB,ABS_IND,FGW,A,NaN,11.18,10.57,11.1,11.91,10.71,11.1,11.24,11.35,PC,POP_PWS,A,NaN,NaN,NaN,NaN,NaN,99.0,99.0,99.0,99.0
15,M3_HAB,ABST,FGW,HR,A,103.21,102.22,103.41,101.17,98.56,101.93,104.96,103.19,104.51,M3_HAB,ABS_PWS,FGW,A,101.31,99.88,101.5,99.37,97.24,100.66,103.53,101.15,102.97,M3_HAB,ABS_IND,FGW,A,1.68,2.12,1.69,1.61,1.18,1.13,1.24,1.89,1.4,PC,POP_PWS,A,93.0,93.0,93.0,92.16,91.6,90.2,87.5,85.5,83.5
16,M3_HAB,ABST,FGW,HU,A,52.6,59.49,49.55,49.89,48.15,50.06,50.74,50.37,49.7,M3_HAB,ABS_PWS,FGW,A,37.92,37.03,35.21,35.66,34.08,33.79,34.73,34.58,34.95,M3_HAB,ABS_IND,FGW,A,NaN,NaN,NaN,NaN,NaN,NaN,3.46,3.81,3.74,PC,POP_PWS,A,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
17,M3_HAB,ABST,FGW,IE,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M3_HAB,ABS_PWS,FGW,A,NaN,21.32,22.22,21.59,25.87,22.13,22.01,21.22,21.76,M3_HAB,ABS_IND,FGW,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PC,POP_PWS,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,M3_HAB,ABST,FGW,IS,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M3_HAB,ABS_PWS,FGW,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M3_HAB,ABS_IND,FGW,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,M3_HAB,ABST,FGW,IT,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M3_HAB,ABS_PWS,FGW,A,129.45,131.81,131.46,131.49,130.84,133.06,135.09,NaN,NaN,M3_HAB,ABS_IND,FGW,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,M3_HAB,ABST,FGW,LT,A,57.99,54.8,54.43,53.72,53.98,53.31,50.13,50.87,50.5,M3_HAB,ABS_PWS,FGW,A,48.29,45.18,45.04,44.3,44.33,43.4,40.04,40.61,40.04,M3_HAB,ABS_IND,FGW,A,2.28,2.11,1.85,1.72,1.59,1.65,1.63,1.32,1.3,PC,POP_PWS,A,82.436,81.838,81.256,80.24,79.4,77.6,76.0,75.0,74.5
21,M3_HAB,ABST,FGW,LU,A,NaN,NaN,39.91,45.83,48.52,46.79,39.82,43.76,46.41,M3_HAB,ABS_PWS,FGW,A,NaN,NaN,39.91,42.16,44.78,42.42,38.11,40.44,45.41,M3_HAB,ABS_IND,FGW,A,NaN,NaN,NaN,1.67,2.36,2.9,1.14,1.56,0.8,PC,POP_PWS,A,NaN,NaN,NaN,99.9,99.9,99.9,99.9,99.9,99.9
22,M3_HAB,ABST,FGW,LV,A,56.24,42.81,41.26,40.54,41.72,43.38,41.55,42.91,44.95,M3_HAB,ABS_PWS,FGW,A,32.24,30.38,30.45,28.86,29.41,29.9,30.09,30.08,28.58,M3_HAB,ABS_IND,FGW,A,4.01,3.94,3.92,3.78,4.03,4.17,3.54,3.47,6.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,M3_HAB,ABST,FGW,MK,A,NaN,NaN,NaN,NaN,100.3,NaN,NaN,NaN,NaN,M3_HAB,ABS_PWS,FGW,A,NaN,NaN,NaN,NaN,NaN,16.68,16.26,NaN,NaN,M3_HAB,ABS_IND,FGW,A,NaN,10.77,NaN,NaN,8.18,11.88,30.49,26.59,56.27,PC,POP_PWS,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,M3_HAB,ABST,FGW,MT,A,81.27,90.77,92.31,89.63,98.81,102.96,89.74,94.65,98.88,M3_HAB,ABS_PWS,FGW,A,29.93,31.2,29.99,30.57,32.51,32.64,31.85,31.47,30.87,M3_HAB,ABS_IND,FGW,A,2.1,2.17,2.22,2.27,2.33,2.37,2.39,2.41,2.42,PC,POP_PWS,A,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
25,M3_HAB,ABST,FGW,NL,A,69.13,59.4,57.92,58.73,57.34,59.12,56.22,59.39,60.16,M3_HAB,ABS_PWS,FGW,A,47.93,45.78,45.81,45.37,45.02,45.46,45.05,45.38,45.9,M3_HAB,ABS_IND,FGW,A,7.7,7.62,8.47,8.48,8.38,8.35,8.02,8.31,8.18,PC,POP_PWS,A,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
26,M3_HAB,ABST,FGW,NO,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M3_HAB,ABS_PWS,FGW,A,22.23,19.72,18.38,NaN,22.71,21.38,20.06,16.06,15.44,M3_HAB,ABS_IND,FGW,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PC,POP_PWS,A,89.315,89.493,89.437,89.481,89.0,89.0,89.0,89.0,88.0
27,M3_HAB,ABST,FGW,PL,A,66.06,67.36,68.31,68.61,67.8,68.52,69.48,71.79,71.58,M3_HAB,ABS_PWS,FGW,A,40.87,38.45,38.82,38.63,37.24,37.2,37.55,37.37,37.49,M3_HAB,ABS_IND,FGW,A,4.48,4.3,4.32,4.25,4.15,4.08,4.1,4.15,3.97,PC,POP_PWS,A,92.1,92.0,91.9,91.8,91.6,88.0,87.9,87.6,87.5
28,M3_HAB,ABST,FGW,PT,A,NaN,200.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M3_HAB,ABS_PWS,FGW,A,NaN,29.68,23.14,22.71,23.68,26.63,28.3,NaN,NaN,M3_HAB,ABS_IND,FGW,A,NaN,7.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PC,POP_PWS,A,NaN,92.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,M3_HAB,ABST,FGW,RO,A,34.61,32.89,32.13,29.69,27.77,29.02,29.76,29.7,30.75,M3_HAB,ABS_PWS,FGW,A,NaN,22.7,22.67,20.83,19.55,19.68,20.05,18.71,18.33,M3_HAB,ABS_IND,FGW,A,NaN,7.28,6.93,6.69,6.32,7.49,7.56,9.21,10.64,PC,POP_PWS,A,69.4,67.5,65.2,63.7,62.5,61.4,60.3,56.5,55.7
30,M3_HAB,ABST,FGW,RS,A,70.87,65.41,62.38,67.09,63.96,66.53,70.03,69.32,70.26,M3_HAB,ABS_PWS,FGW,A,61.09,55.58,53.87,60.53,59.92,61.51,65.27,65.19,65.78,M3_HAB,ABS_IND,FGW,A,4.18,4.12,3.62,3.51,3.29,3.77,3.49,3.34,3.74,PC,POP_PWS,A,87.9,86.9,85.9,85.0,83.7,81.9,80.1,78.2,77.7
31,M3_HAB,ABST,FGW,SE,A,NaN,NaN,NaN,37.45,NaN,NaN,NaN,NaN,36.94,M3_HAB,ABS_PWS,FGW,A,NaN,NaN,NaN,20.01,NaN,NaN,NaN,NaN,22.38,M3_HAB,ABS_IND,FGW,A,NaN,NaN,NaN,1.33,NaN,NaN,NaN,NaN,1.39,PC,POP_PWS,A,NaN,NaN,NaN,87.6,87.0,87.0,86.0,86.0,86.8
32,M3_HAB,ABST,FGW,SI,A,91.75,91.24,87.25,88.03,88.21,87.96,87.38,90.09,90.47,M3_HAB,ABS_PWS,FGW,A,81.96,81.32,77.66,78.63,77.92,78.05,77.06,80.38,79.24,M3_HAB,ABS_IND,FGW,A,9.19,9.25,9.01,8.97,9.95,9.52,9.92,9.32,10.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,M3_HAB,ABST,FGW,SK,A,62.26,61.54,59.58,60.1,59.32,60.84,62.71,62.01,63.3,M3_HAB,ABS_PWS,FGW,A,45.12,45.26,44.25,44.58,44.41,45.76,47.5,47.07,48.4,M3_HAB,ABS_IND,FGW,A,10.6,9.6,9.29,9.28,8.99,9.3,9.44,9.03,9.0,PC,POP_PWS,A,89.3,88.9,88.7,88.3,87.7,87.4,87.0,86.9,86.6
34,M3_HAB,ABST,FGW,TR,A,200.22,193.7,191.26,187.91,190.43,179.3,181.47,183.93,181.06,M3_HAB,ABS_PWS,FGW,A,40.46,40.14,37.28,37.13,36.96,40.54,44.14,44.61,44.56,M3_HAB,ABS_IND,FGW,A,6.9,NaN,6.51,NaN,6.19,NaN,5.65,NaN,8.07,PC,POP_PWS,A,98.61,NaN,98.3,NaN,97.4,NaN,98.3,NaN,98.3
35,M3_HAB,ABST,FGW,UK,A,NaN,NaN,NaN,NaN,31.9,NaN,32.22,34.25,34.43,M3_HAB,ABS_PWS,FGW,A,NaN,NaN,NaN,NaN,25.86,NaN,26.52,27.66,27.64,M3_HAB,ABS_IND,FGW,A,NaN,NaN,NaN,NaN,2.63,NaN,2.71,2.99,3.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,M3_HAB,ABST,FGW,UKC-L,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M3_HAB,ABS_PWS,FGW,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M3_HAB,ABS_IND,FGW,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,M3_HAB,ABST,FGW,XK,A,9.11,8.41,10.05,NaN,NaN,NaN,NaN,NaN,NaN,M3_HAB,ABS_PWS,FGW,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M3_HAB,ABS_IND,FGW,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Corporate Tax

In [45]:
Tax = pd.read_html('https://taxfoundation.org/integrated-tax-rates-on-corporate-income-in-europe')[0]
Tax = Tax.loc[0:26,:]

In [46]:
for col in Tax.columns:
    print(col)

('OECD Country', 'OECD Country')
('Statutory Corporate Income Tax Rate', 'Statutory Corporate Income Tax Rate')
('Dividends', 'Top Personal Dividend Tax Rate')
('Dividends', 'Integrated Tax on Corporate Income (Dividends)')
('Capital Gains (a)', 'Top Personal Capital Gains Tax Rate')
('Capital Gains (a)', 'Integrated Tax on Corporate Income (Capital Gains)')

In [47]:
Tax

            OECD Country Statutory Corporate Income Tax Rate  \
            OECD Country Statutory Corporate Income Tax Rate
0           Austria (AT)                               25.0%
1           Belgium (BE)                               29.0%
2    Czech Republic (CZ)                               19.0%
3           Denmark (DK)                               22.0%
4           Estonia (EE)                               20.0%
5           Finland (FI)                               20.0%
6            France (FR)                               32.0%
7           Germany (DE)                               29.9%
8            Greece (GR)                               24.0%
9           Hungary (HU)                                9.0%
10          Iceland (IS)                               20.0%
11          Ireland (IE)                               12.5%
12            Italy (IT)                               24.0%
13           Latvia (LV)                               20.0%
14        Lithuania (LT)                               15.0%
15       Luxembourg (LU)                               24.9%
16      Netherlands (NL)                               25.0%
17           Norway (NO)                               22.0%
18           Poland (PL)                               19.0%
19         Portugal (PT)                               31.5%
20  Slovak Republic (SK)                               21.0%
21         Slovenia (SI)                               19.0%
22            Spain (ES)                               25.0%
23           Sweden (SE)                               21.4%
24      Switzerland (CH)                               21.1%
25           Turkey (TR)                               22.0%
26   United Kingdom (GB)                               19.0%

                        Dividends  \
   Top Personal Dividend Tax Rate
0                           27.5%
1                           30.0%
2                           15.0%
3                           42.0%
4                            0.0%
5                           28.9%
6                           34.0%
7                           26.4%
8                            5.0%
9                           15.0%
10                          22.0%
11                          51.0%
12                          26.0%
13                           0.0%
14                          15.0%
15                          21.0%
16                          25.0%
17                          31.7%
18                          19.0%
19                          28.0%
20                           7.0%
21                          27.5%
22                          23.0%
23                          30.0%
24                          22.3%
25                          20.0%
26                          38.1%

                                                   \
   Integrated Tax on Corporate Income (Dividends)
0                                           45.6%
1                                           50.3%
2                                           31.2%
3                                           54.8%
4                                           20.0%
5                                           43.1%
6                                           55.1%
7                                           48.4%
8                                           27.8%
9                                           22.7%
10                                          37.6%
11                                          57.1%
12                                          43.8%
13                                          20.0%
14                                          27.8%
15                                          40.7%
16                                          43.8%
17                                          46.7%
18                                          34.4%
19                                          50.7%
20                                          26.5%
21                                          41.3%
22                                          42.3%
23                                          45.0%
24                                          38.7%
25                                          37.6%
26                                          49.9%

                     Capital Gains (a)  \
   Top Personal Capital Gains Tax Rate
0                                27.5%
1                                 0.0%
2                                 0.0%
3                                42.0%
4                                20.0%
5                                34.0%
6                                30.0%
7                                26.4%
8                                15.0%
9                                15.0%
10                               22.0%
11                               33.0%
12                               26.0%
13                               20.0%
14                               20.0%
15                                0.0%
16                               30.0%
17                               31.7%
18                               19.0%
19                               28.0%
20                                0.0%
21                                0.0%
22                               23.0%
23                               30.0%
24                                0.0%
25                                0.0%
26                               20.0%


   Integrated Tax on Corporate Income (Capital Gains)
0                                               45.6%
1                                               29.0%
2                                               19.0%
3                                               54.8%
4                                               36.0%
5                                               47.2%
6                                               52.4%
7                                               48.4%
8                                               35.4%
9                                               22.7%
10                                              37.6%
11                                              41.4%
12                                              43.8%
13                                              36.0%
14                                              32.0%
15                                              24.9%
16                                              47.5%
17                                              46.7%
18                                              34.4%
19                                              50.7%
20                                              21.0%
21                                              19.0%
22                                              42.3%
23                                              45.0%
24                                              21.1%
25                                              22.0%
26                                              35.2%

In [48]:
Tax = Tax.rename({"OECD Country": "GEO","Statutory Corporate Income Tax Rate":"SC_Inc_Tax"}, axis =1)

In [49]:
Tax.dtypes

GEO                GEO                                                   object
SC_Inc_Tax         SC_Inc_Tax                                            object
Dividends          Top Personal Dividend Tax Rate                        object
                   Integrated Tax on Corporate Income (Dividends)        object
Capital Gains (a)  Top Personal Capital Gains Tax Rate                   object
                   Integrated Tax on Corporate Income (Capital Gains)    object
dtype: object

In [50]:
Tax['GEO'] = Tax['GEO'].astype(str)

In [51]:
Tax.dtypes

GEO                GEO                                                   object
SC_Inc_Tax         SC_Inc_Tax                                            object
Dividends          Top Personal Dividend Tax Rate                        object
                   Integrated Tax on Corporate Income (Dividends)        object
Capital Gains (a)  Top Personal Capital Gains Tax Rate                   object
                   Integrated Tax on Corporate Income (Capital Gains)    object
dtype: object

In [52]:
Tax = Tax.convert_dtypes()
Tax.dtypes

GEO                GEO                                                   string
SC_Inc_Tax         SC_Inc_Tax                                            string
Dividends          Top Personal Dividend Tax Rate                        string
                   Integrated Tax on Corporate Income (Dividends)        string
Capital Gains (a)  Top Personal Capital Gains Tax Rate                   string
                   Integrated Tax on Corporate Income (Capital Gains)    string
dtype: object

In [53]:
Tax['GEO'] = Tax['GEO'].str.extract(r"\(([A-Za-z]+)\)", expand=False)

AttributeError: 'DataFrame' object has no attribute 'str'

## Data Pannel:- GDP and EDUCATION NUTS2

In [54]:
EU_NUTS2_GDP_EDU = pd.merge(EU_NUTS2_EDU_ALL,EU_NUTS2_GDP_ALL,on='GEO', how='left', suffixes=('', '_drop'))
EU_NUTS2_GDP_EDU = EU_NUTS2_GDP_EDU.drop(['ISCED11','UNIT','SEX','FREQ_x','ISCED11_x','ISCED11_y','UNIT_x','UNIT_y',
                                        'SEX_x','SEX_y','FREQ_y','FREQ_x_drop','Unit_2','FREQ_y_drop','Unit_1'], axis =1 )
EU_NUTS2_GDP_EDU

,GEO,FREQ,EDU_2019_ED8,EDU_2018_ED8,EDU_2017_ED8,EDU_2016_ED8,EDU_2015_ED8,EDU_2014_ED8,EDU_2013_ED8,EDU_2019_ED7,EDU_2018_ED7,EDU_2017_ED7,EDU_2016_ED7,EDU_2015_ED7,EDU_2014_ED7,EDU_2013_ED7,EDU_2019_ED6,EDU_2018_ED6,EDU_2017_ED6,EDU_2016_ED6,EDU_2015_ED6,EDU_2014_ED6,EDU_2013_ED6,GDP_2019_M,GDP_2018_M,GDP_2017_M,GDP_2016_M,GDP_2015_M,GDP_2014_M,GDP_2013_M,GDP_2012_M,GDP_2011_M,GDP_2010_M,GDP_2019,GDP_2018,GDP_2017,GDP_2016,GDP_2015,GDP_2014,GDP_2013,GDP_2012,GDP_2011,GDP_2010
0,AT1,A,10625.0,11350.0,NaN,13412.0,13733.0,13920.0,14395.0,76419.0,76482.0,NaN,75707.0,76682.0,76049.0,75890.0,113027.0,115414.0,NaN,110813.0,105550.0,102896.0,103050.0,171326.17,166154.65,159941.08,155864.94,149210.45,144536.29,141127.14,139149.68,136271.77,131114.27,44200.0,43100.0,41700.0,41000.0,39800.0,39100.0,38500.0,38300.0,37800.0,36600.0
1,AT11,A,0.0,0.0,NaN,0.0,0.0,0.0,0.0,2593.0,2097.0,NaN,1350.0,1243.0,1128.0,718.0,1571.0,1750.0,NaN,1418.0,1366.0,1180.0,1115.0,9272.61,8981.06,8752.62,8351.77,8040.55,7737.13,7539.32,7365.43,7012.58,6698.37,31600.0,30700.0,30000.0,28600.0,27800.0,26900.0,26300.0,25700.0,24600.0,23600.0
2,AT12,A,24.0,17.0,NaN,4.0,2.0,3.0,3.0,12568.0,12308.0,NaN,11301.0,10815.0,9905.0,8641.0,8091.0,9134.0,NaN,6876.0,6631.0,6462.0,6268.0,61706.24,60114.35,58027.88,55570.83,53884.36,52049.38,50470.13,49802.6,48511.33,46285.86,36700.0,35900.0,34800.0,33500.0,32800.0,31900.0,31100.0,30800.0,30100.0,28800.0
3,AT13,A,10601.0,11333.0,NaN,13408.0,13731.0,13917.0,14392.0,61258.0,62077.0,NaN,63055.0,64624.0,65016.0,66531.0,103365.0,104530.0,NaN,102519.0,97554.0,95253.0,95667.0,100347.32,97058.12,93159.46,91942.34,87284.43,84749.78,83117.69,81981.66,80747.86,78130.05,52700.0,51300.0,49600.0,49600.0,48100.0,47600.0,47400.0,47500.0,47300.0,46100.0
4,AT2,A,3792.0,4060.0,NaN,4410.0,4520.0,4625.0,4930.0,22063.0,23346.0,NaN,25252.0,25944.0,26700.0,26474.0,37175.0,37106.0,NaN,35793.0,34687.0,33837.0,34543.0,72337.07,69810.54,67341.13,64637.92,62439.56,61130.4,59211.38,58727.86,57015.06,54158.24,40100.0,38700.0,37400.0,36000.0,35000.0,34400.0,33500.0,33300.0,32300.0,30700.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,TRB1,A,2200.0,NaN,NaN,1778.0,1563.0,1175.0,1776.0,12232.0,NaN,NaN,10590.0,8989.0,7526.0,6669.0,66516.0,NaN,NaN,60517.0,56684.0,51946.0,46955.0,8684.94,8288.39,9877.99,10171.94,9982.53,9105.19,9560.26,9082.6,8083.86,7793.51,4900.0,4800.0,5700.0,6000.0,5900.0,5400.0,5700.0,5400.0,4900.0,4800.0
334,TRB2,A,587.0,NaN,NaN,297.0,354.0,139.0,462.0,7296.0,NaN,NaN,6936.0,5420.0,3966.0,3878.0,22082.0,NaN,NaN,22525.0,21751.0,19750.0,17698.0,7388.44,6898.96,7986.81,8309.77,8003.34,7509.0,7759.79,8200.98,6449.98,6370.9,3400.0,3200.0,3800.0,3900.0,3800.0,3600.0,3700.0,4000.0,3200.0,3200.0
335,TRC1,A,982.0,NaN,NaN,1060.0,942.0,433.0,639.0,10701.0,NaN,NaN,12118.0,9506.0,8269.0,7202.0,44568.0,NaN,NaN,44763.0,40291.0,34855.0,30372.0,14989.71,14637.14,16518.67,17015.64,17015.04,14908.19,14946.37,13546.61,11257.49,10649.54,5300.0,5300.0,6000.0,6300.0,6400.0,5700.0,5900.0,5400.0,4600.0,4500.0
336,TRC2,A,870.0,NaN,NaN,835.0,643.0,103.0,1049.0,8273.0,NaN,NaN,7901.0,6394.0,3888.0,5452.0,30258.0,NaN,NaN,29746.0,29157.0,28546.0,27530.0,12131.71,11630.85,14073.93,14683.24,14740.71,13221.9,14050.38,13078.78,11515.82,11320.93,3200.0,3100.0,3900.0,4100.0,4200.0,3800.0,4200.0,3900.0,3600.0,3600.0
337,TRC3,A,93.0,NaN,NaN,64.0,51.0,15.0,0.0,3059.0,NaN,NaN,2046.0,1351.0,515.0,129.0,20053.0,NaN,NaN,13489.0,11072.0,9111.0,7230.0,9653.76,9049.97,10308.14,10092.76,10105.88,9529.04,9685.71,9077.42,7892.19,7679.69,4200.0,4000.0,4700.0,4600.0,4700.0,4500.0,4600.0,4400.0,3900.0,3900.0

In [55]:
EU_NUTS2_GDP_EDU.to_pickle("NUTS2.pkl")